version: "#{build}"
build:
  verbosity: detailed
install:
  - cinst jdk9 -version 9.0.4.11 -params 'installdir=C:\\jdk9'
  - SET JAVA_HOME=C:\jdk9
  - SET PATH=C:\jdk9\bin;%PATH%
build_script:
  - mvnw clean package

